version: '3.9'
services:
    java-maven-app:
      image: $selftaughdevops/java-maven-app:1.0-SNAPSHOT
      ports:
        - 8080:8080
    postgres:
      image: postgres:13
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=my-password
